version: '3.8'
services:
  devcontainer:
    build: 
      context: ../
      dockerfile: .devcontainer/Dockerfile
      args:
        SSO_START_URL: $SSO_START_URL
        SSO_ACCOUNT_ID: $SSO_ACCOUNT_ID
        SSO_REGION: $SSO_REGION

    volumes:
      - ..:/workspaces:cached
    command: sleep infinity

networks:
  default:
    name: whtwnd_devcontainer